//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lenovodisplay
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lenovo
    {
        public string ServiceID { get; set; }
        public System.DateTime PDate { get; set; }
        public string OwnerName { get; set; }
        public string Contact { get; set; }
        public string DeviceType { get; set; }
        public string SerialNo { get; set; }
        public string IssueDescription { get; set; }
    }
}
